# ========================================
# Powerlevel10k 設定ファイル
# ========================================
# 使用フォント: MesloLGS NF
# ※WSL2の場合はWindows側にフォントをインストール後ターミナル設定でフォント指定
# ========================================
# p10k configure で再設定可能
# ========================================

# Generated by Powerlevel10k configuration wizard on 2024-10-08 at 01:02 JST.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 44011.
# Wizard options: nerdfont-v3 + powerline, small icons, rainbow, unicode, 24h time,
# round separators, round heads, round tails, 2 lines, disconnected, no frame, sparse,
# many icons, concise, instant_prompt=verbose.

# カラーマップ表示用コマンド:
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# ============================================================
# Theme Select
# ============================================================
# cyberpunk / gruvbox
typeset -g P10K_THEME="cyberpunk"

# オプションの一時変更
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # 設定リセット
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh 5.1以上が必要
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # ============================================================
  # Theme Palette
  # ============================================================

  case "$P10K_THEME" in
    cyberpunk)
      # ========================================================
      # 🌃 Cyberpunk Theme
      # ========================================================

      # Base
      local -r C_DARK=236
      local -r C_WHITE=255
      local -r C_BLACK=0
      # Primary

      local -r C_INDIGO=57
      local -r C_NEON_PURPLE=93

      # Semantic
      local -r C_SUCCESS=48
      local -r C_SUCCESS_ALT=37
      local -r C_WARNING=93
      local -r C_ERROR=198

      # VCS
      typeset -g C_VCS_CLEAN_FG=0
      typeset -g C_VCS_MODIFIED_FG=255
      typeset -g C_VCS_UNTRACKED_FG=255
      typeset -g C_VCS_CONFLICTED_FG=255

      ;;
    gruvbox)

      # ========================================================
      # 🌿 Gruvbox Theme
      # ========================================================
      # Base
      local -r C_DARK=235
      local -r C_WHITE=223
      local -r C_BLACK=234

      # Primary
      local -r C_INDIGO=66
      local -r C_NEON_PURPLE=95

      # Semantic
      local -r C_SUCCESS=108
      local -r C_SUCCESS_ALT=142
      local -r C_WARNING=136
      local -r C_ERROR=167

      # VCS
      typeset -g C_VCS_CLEAN_FG=234
      typeset -g C_VCS_MODIFIED_FG=223
      typeset -g C_VCS_UNTRACKED_FG=136
      typeset -g C_VCS_CONFLICTED_FG=167
      ;;
    *)
      print -P "%F{red}[p10k] Unknown theme: $P10K_THEME%f"
      return 1
      ;;

  esac

  # ============================================================
  # 左プロンプト要素
  # ============================================================
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # === 1行目 ===
    os_icon                 # OS アイコン
    dir                     # カレントディレクトリ
    vcs                     # Git ステータス
    # === 2行目 ===
    newline                 # 改行
    prompt_char             # プロンプト記号
  )

  # ============================================================
  # 右プロンプト要素
  # ============================================================
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # === 1行目 ===
    status                  # 終了コード
    command_execution_time  # コマンド実行時間
    background_jobs         # バックグラウンドジョブ
    direnv                  # direnv 状態
    asdf                    # asdf バージョン管理
    virtualenv              # Python 仮想環境
    anaconda                # conda 環境
    pyenv                   # Python 環境
    goenv                   # Go 環境
    nodenv                  # Node.js (nodenv)
    nvm                     # Node.js (nvm)
    nodeenv                 # Node.js 環境
    # node_version          # Node.js バージョン
    # go_version            # Go バージョン
    # rust_version          # Rust バージョン
    # dotnet_version        # .NET バージョン
    # php_version           # PHP バージョン
    # laravel_version       # Laravel バージョン
    # java_version          # Java バージョン
    # package               # package.json の name@version
    rbenv                   # Ruby (rbenv)
    rvm                     # Ruby (rvm)
    fvm                     # Flutter (fvm)
    luaenv                  # Lua (luaenv)
    jenv                    # Java (jenv)
    plenv                   # Perl (plenv)
    perlbrew                # Perl (perlbrew)
    phpenv                  # PHP (phpenv)
    scalaenv                # Scala (scalaenv)
    haskell_stack           # Haskell (stack)
    kubecontext             # Kubernetes コンテキスト
    terraform               # Terraform ワークスペース
    # terraform_version     # Terraform バージョン
    aws                     # AWS プロファイル
    aws_eb_env              # AWS Elastic Beanstalk
    azure                   # Azure アカウント
    gcloud                  # Google Cloud
    google_app_cred         # Google 認証情報
    toolbox                 # Toolbox 名
    context                 # user@hostname
    nordvpn                 # NordVPN 状態 (Linux)
    ranger                  # ranger シェル
    yazi                    # yazi シェル
    nnn                     # nnn シェル
    lf                      # lf シェル
    xplr                    # xplr シェル
    vim_shell               # vim シェル (:sh)
    midnight_commander      # mc シェル
    nix_shell               # nix シェル
    chezmoi_shell           # chezmoi シェル
    vi_mode                 # vi モード (prompt_char有効時は不要)
    # vpn_ip                # VPN 接続状態
    # load                  # CPU 負荷
    # disk_usage            # ディスク使用量
    # ram                   # メモリ使用量
    # swap                  # スワップ使用量
    todo                    # todo.txt タスク数
    timewarrior             # Timewarrior 追跡状態
    taskwarrior             # Taskwarrior タスク数
    per_directory_history   # ディレクトリ別履歴 (OMZ)
    # cpu_arch              # CPU アーキテクチャ
    time                    # 現在時刻
    # === 2行目 ===
    newline
    # ip                    # IP アドレス / 帯域
    # public_ip             # パブリック IP
    # proxy                 # プロキシ設定
    # battery               # バッテリー
    # wifi                  # WiFi 速度
    # example               # カスタムセグメント例
  )

  # ============================================================
  # 基本設定
  # ============================================================
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  # アイコンパディング: none=なし / moderate=少し余白
  typeset -g POWERLEVEL9K_ICON_PADDING=none
  # アイコン位置: 空=左は前/右は後 / true=両方前 / false=両方後
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=

  # ============================================================
  # 余白設定 (Whitespace)
  # ============================================================
  # グローバル余白（左プロンプト）
  typeset -g POWERLEVEL9K_LEFT_LEFT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_LEFT_RIGHT_WHITESPACE=' '
  # グローバル余白（右プロンプト）
  typeset -g POWERLEVEL9K_RIGHT_LEFT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_RIGHT_RIGHT_WHITESPACE=' '

  # セグメント内部の余白
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_PYENV_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_ANACONDA_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_NODENV_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_NVM_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_GOENV_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_RBENV_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_{LEFT,RIGHT}_WHITESPACE=' '
  typeset -g POWERLEVEL9K_TIME_{LEFT,RIGHT}_WHITESPACE=' '

  # ============================================================
  # プロンプトレイアウト
  # ============================================================
  # 各プロンプトの前に空行を追加
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # 左プロンプトの行接続記号
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  # 右プロンプトの行接続記号
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # 左右プロンプト間の埋め文字 (' ', '·', '─')
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=$C_NEUTRAL_700
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # ============================================================
  # セグメント区切り記号 - シャープ/アングル型 (Cyberpunk)
  # ============================================================
  # 同色セグメント間の区切り (シャープ)
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
  # 異色セグメント間の区切り (シャープ)
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'

  # プロンプト端の記号 (シャープ + 端は丸み)
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  # ============================================================
  # os_icon: OS アイコン
  # ============================================================
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$C_DARK

  # ============================================================
  # prompt_char: プロンプト記号
  # ============================================================
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  # 成功時: シアングリーン
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$C_SUCCESS
  # 失敗時: ホットピンク
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$C_ERROR
  # 各モードの記号
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  # ============================================================
  # dir: カレントディレクトリ
  # ============================================================
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$C_WHITE
  # フォルダアイコン (デフォルト + 右にスペース)
  typeset -g POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER} '
  # 長いパスを短縮 (一意になる最短プレフィックスに)
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  # 短縮部分の色
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=189
  # アンカー(短縮しない)部分の色
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  # アンカーファイル (これらを含むディレクトリは短縮しない)
  local anchor_files=(
    .bzr
    .citc
    .git
    .hg
    .node-version
    .python-version
    .go-version
    .ruby-version
    .lua-version
    .java-version
    .perl-version
    .php-version
    .tool-versions
    .shorten_folder_marker
    .svn
    .terraform
    CVS
    Cargo.toml
    composer.json
    go.mod
    package.json
    stack.yaml
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  # ハイパーリンク有効化 (クリックでファイルマネージャを開く)
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  # 書き込み不可/存在しないディレクトリの表示
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # ============================================================
  # vcs: Git ステータス
  # ============================================================
  # GitHub ロゴアイコン
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=$'\uf09b '

  # 前景色 (アイコン・テキスト) - 一元管理された色定義を参照
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$C_VCS_CLEAN_FG
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$C_VCS_MODIFIED_FG
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$C_VCS_UNTRACKED_FG
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$C_VCS_CONFLICTED_FG
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$C_VCS_CLEAN_FG

  # 背景色 (状態別) - Cyberpunk
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$C_SUCCESS_ALT
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=$C_ERROR
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=$C_DARK

  # ブランチアイコン
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  # 未追跡ファイルアイコン
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Git ステータスのフォーマッタ
  # 出力例: master wip ⇣42⇡42 *42 merge ~42 +42 !42 ?42
  function my_git_formatter() {
    emulate -L zsh


    # 色設定 - 状態に応じて色を決定（一元管理）
    # グローバル変数C_VCS_*_FGを参照
    local text_color

    # 変更がある場合は白、クリーンな場合は黒
    # 算術評価で確実にチェック
    if (( ${VCS_STATUS_NUM_STAGED:-0} > 0 )) || \
       (( ${VCS_STATUS_NUM_UNSTAGED:-0} > 0 )) || \
       (( ${VCS_STATUS_NUM_UNTRACKED:-0} > 0 )) || \
       (( ${VCS_STATUS_NUM_CONFLICTED:-0} > 0 )); then
      # 変更あり → カラーパレットから取得
      text_color="%${C_VCS_MODIFIED_FG}F"
    else
      # クリーン → カラーパレットから取得
      text_color="%${C_VCS_CLEAN_FG}F"
    fi

    # 全ての要素に同じ色を適用（アイコンとテキストを統一）
    local       meta="$text_color"              # メタ情報
    local      clean="$text_color"              # クリーン状態
    local   modified="$text_color"              # 変更あり
    local  untracked="$text_color"              # 未追跡
    local conflicted="$text_color"              # コンフリクト

    local res

    # ブランチ名 (32文字超は省略)
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      local branch=${(V)VCS_STATUS_LOCAL_BRANCH}
      (( $#branch > 32 )) && branch[13,-13]="…"
      res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}${branch//\%/%%}"
    fi

    # タグ名 (ブランチがない場合のみ表示)
    if [[ -n $VCS_STATUS_TAG && -z $VCS_STATUS_LOCAL_BRANCH ]]; then
      local tag=${(V)VCS_STATUS_TAG}
      (( $#tag > 32 )) && tag[13,-13]="…"
      res+="${meta}#${clean}${tag//\%/%%}"
    fi

    # コミットハッシュ (ブランチもタグもない場合)
    [[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_TAG ]] &&
      res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"

    # リモートブランチ名 (ローカルと異なる場合)
    if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
      res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"
    fi

    # WIP 表示 (コミットメッセージに wip/WIP を含む場合)
    if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
      res+=" ${modified}wip"
    fi

    # リモートとの差分
    if (( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND )); then
      (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}"
      (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
      (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
    fi

    # プッシュリモートとの差分
    (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" ${clean}⇠${VCS_STATUS_PUSH_COMMITS_BEHIND}"
    (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" "
    (( VCS_STATUS_PUSH_COMMITS_AHEAD  )) && res+="${clean}⇢${VCS_STATUS_PUSH_COMMITS_AHEAD}"
    # スタッシュ数
    (( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}"
    # マージ/リベース中などの特殊状態
    [[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}"
    # コンフリクト数
    (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}~${VCS_STATUS_NUM_CONFLICTED}"
    # ステージ済み変更数
    (( VCS_STATUS_NUM_STAGED     )) && res+=" ${modified}+${VCS_STATUS_NUM_STAGED}"
    # 未ステージ変更数
    (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
    # 未追跡ファイル数
    (( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON}${VCS_STATUS_NUM_UNTRACKED}"
    # 不明 (インデックスが大きすぎる場合)
    (( VCS_STATUS_HAS_UNSTAGED == -1 )) && res+=" ${modified}─"

    typeset -g my_git_format=$res
  }
  functions -M my_git_formatter 2>/dev/null

  # 大規模リポジトリでのダーティチェック上限 (負数=無制限)
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
  # Git ステータスを無効化するディレクトリパターン
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
  # カスタムフォーマッタを使用
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1
  # 対応 VCS (git のみ推奨 / svn, hg は遅くなる)
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

  # ============================================================
  # status: 終了コード
  # ============================================================
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true

  # 成功時 - シアングリーン
  typeset -g POWERLEVEL9K_STATUS_OK=true
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=$C_SUCCESS

  # パイプの一部が失敗 (全体は成功) 例: 1|0
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=$C_SUCCESS_ALT

  # エラー時 - ホットピンク
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=$C_ERROR

  # シグナルで終了時
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=$C_ERROR

  # パイプの一部が失敗 (全体も失敗) 例: 1|0
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=$C_ERROR

  # ============================================================
  # command_execution_time: コマンド実行時間
  # ============================================================
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=$C_WARNING
  # この秒数以上で表示
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  # 小数点以下の桁数 (0=秒単位)
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  # 表示フォーマット
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # ============================================================
  # background_jobs: バックグラウンドジョブ
  # ============================================================
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=$C_DARK
  # ジョブ数を表示しない
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

  # ============================================================
  # direnv: direnv 状態
  # ============================================================
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=$C_NEON_PURPLE

  # ============================================================
  # asdf: asdf バージョン管理
  # ============================================================
  typeset -g POWERLEVEL9K_ASDF_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_BACKGROUND=$C_INDIGO

  # バージョンソース (shell, local, global)
  typeset -g POWERLEVEL9K_ASDF_SOURCES=(shell local global)
  # グローバルと同じ場合は非表示
  typeset -g POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false
  # system の場合も表示
  typeset -g POWERLEVEL9K_ASDF_SHOW_SYSTEM=true
  # 特定ファイルがある場合のみ表示
  typeset -g POWERLEVEL9K_ASDF_SHOW_ON_UPGLOB=

  # 言語別の色設定 - Cyberpunk (6色統一)
  typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_RUBY_BACKGROUND=$C_ERROR

  typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_PYTHON_BACKGROUND=$C_INDIGO

  typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_ASDF_GOLANG_BACKGROUND=$C_SUCCESS_ALT

  typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_ASDF_NODEJS_BACKGROUND=$C_SUCCESS

  typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_RUST_BACKGROUND=$C_NEON_PURPLE

  typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_BACKGROUND=$C_NEON_PURPLE

  typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_ASDF_FLUTTER_BACKGROUND=$C_SUCCESS_ALT

  typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_LUA_BACKGROUND=$C_INDIGO

  typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_JAVA_BACKGROUND=$C_NEON_PURPLE

  typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_PERL_BACKGROUND=$C_INDIGO

  typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_ERLANG_BACKGROUND=$C_ERROR

  typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_ELIXIR_BACKGROUND=$C_NEON_PURPLE

  typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_ASDF_POSTGRES_BACKGROUND=$C_SUCCESS_ALT

  typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_PHP_BACKGROUND=$C_NEON_PURPLE

  typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ASDF_HASKELL_BACKGROUND=$C_NEON_PURPLE

  typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_ASDF_JULIA_BACKGROUND=$C_SUCCESS

  # ============================================================
  # nordvpn: NordVPN 状態 (Linux)
  # ============================================================
  typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_NORDVPN_BACKGROUND=$C_SUCCESS_ALT
  # 未接続時は非表示
  typeset -g POWERLEVEL9K_NORDVPN_{DISCONNECTED,CONNECTING,DISCONNECTING}_CONTENT_EXPANSION=
  typeset -g POWERLEVEL9K_NORDVPN_{DISCONNECTED,CONNECTING,DISCONNECTING}_VISUAL_IDENTIFIER_EXPANSION=

  # ============================================================
  # ファイルマネージャシェル
  # ============================================================
  # ranger
  typeset -g POWERLEVEL9K_RANGER_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_RANGER_BACKGROUND=$C_DARK

  # yazi
  typeset -g POWERLEVEL9K_YAZI_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_YAZI_BACKGROUND=$C_DARK

  # nnn
  typeset -g POWERLEVEL9K_NNN_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_NNN_BACKGROUND=$C_DARK

  # lf
  typeset -g POWERLEVEL9K_LF_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_LF_BACKGROUND=$C_DARK

  # xplr
  typeset -g POWERLEVEL9K_XPLR_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_XPLR_BACKGROUND=$C_DARK

  # ============================================================
  # vim_shell: vim シェル (:sh)
  # ============================================================
  typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_VIM_SHELL_BACKGROUND=$C_SUCCESS

  # ============================================================
  # midnight_commander: mc シェル
  # ============================================================
  typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # nix_shell: nix シェル
  # ============================================================
  typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_NIX_SHELL_BACKGROUND=$C_INDIGO

  # ============================================================
  # chezmoi_shell: chezmoi シェル
  # ============================================================
  typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_CHEZMOI_SHELL_BACKGROUND=$C_NEON_PURPLE

  # ============================================================
  # disk_usage: ディスク使用量
  # ============================================================
  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_BACKGROUND=$C_WARNING
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_BACKGROUND=$C_ERROR
  # 警告/危険の閾値 (%)
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=90
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=95
  # 警告レベル未満は非表示
  typeset -g POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false

  # ============================================================
  # vi_mode: vi モード表示
  # ============================================================
  typeset -g POWERLEVEL9K_VI_MODE_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
  typeset -g POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_VI_VISUAL_MODE_STRING=VISUAL
  typeset -g POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=$C_WARNING
  typeset -g POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OVERTYPE
  typeset -g POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND=$C_ERROR
  typeset -g POWERLEVEL9K_VI_INSERT_MODE_STRING=
  typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=$C_SUCCESS

  # ============================================================
  # ram: メモリ使用量
  # ============================================================
  typeset -g POWERLEVEL9K_RAM_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_RAM_BACKGROUND=$C_NEON_PURPLE

  # ============================================================
  # swap: スワップ使用量
  # ============================================================
  typeset -g POWERLEVEL9K_SWAP_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_SWAP_BACKGROUND=$C_WARNING

  # ============================================================
  # load: CPU 負荷
  # ============================================================
  # 平均負荷の期間 (1, 5, 15 分)
  typeset -g POWERLEVEL9K_LOAD_WHICH=5
  typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_LOAD_NORMAL_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_LOAD_WARNING_BACKGROUND=$C_WARNING
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND=$C_ERROR

  # ============================================================
  # todo: todo.txt タスク数
  # ============================================================
  typeset -g POWERLEVEL9K_TODO_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_TODO_BACKGROUND=$C_INDIGO
  # タスクがない場合は非表示
  typeset -g POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=true
  typeset -g POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=false

  # ============================================================
  # timewarrior: 時間追跡状態
  # ============================================================
  typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_TIMEWARRIOR_BACKGROUND=$C_SUCCESS_ALT
  # 24文字超は省略
  typeset -g POWERLEVEL9K_TIMEWARRIOR_CONTENT_EXPANSION='${P9K_CONTENT:0:24}${${P9K_CONTENT:24}:+…}'

  # ============================================================
  # taskwarrior: タスク数
  # ============================================================
  typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_TASKWARRIOR_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # per_directory_history: ディレクトリ別履歴 (OMZ)
  # ============================================================
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # cpu_arch: CPU アーキテクチャ
  # ============================================================
  typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_CPU_ARCH_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # context: user@hostname
  # ============================================================
  # root 時 - ホットピンク
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=$C_ERROR
  # SSH 接続時 - ネオンパープル
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=$C_NEON_PURPLE
  # 通常時
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=$C_DARK
  # フォーマット
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  # root/SSH 以外では非表示
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # ============================================================
  # Python 系 - Cyberpunk (インディゴ背景)
  # ============================================================
  # virtualenv: Python 仮想環境
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=$C_INDIGO
  # Python バージョンは非表示
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  # pyenv と重複時は非表示
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  # anaconda: conda 環境
  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'

  # pyenv
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PYENV_SHOW_SYSTEM=true
  typeset -g POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT}${${P9K_CONTENT:#$P9K_PYENV_PYTHON_VERSION(|/*)}:+ $P9K_PYENV_PYTHON_VERSION}'

  # ============================================================
  # Node.js 系 - Cyberpunk (シアン背景)
  # ============================================================
  # nodenv
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=true

  # nvm
  typeset -g POWERLEVEL9K_NVM_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_NVM_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_NVM_SHOW_SYSTEM=true

  # nodeenv
  typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_NODEENV_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION=false
  typeset -g POWERLEVEL9K_NODEENV_{LEFT,RIGHT}_DELIMITER=

  # node_version
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=$C_SUCCESS
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # package.json
  typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_PACKAGE_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # Go 系 - Cyberpunk (アクア背景)
  # ============================================================
  # goenv
  typeset -g POWERLEVEL9K_GOENV_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_GOENV_BACKGROUND=$C_SUCCESS_ALT
  typeset -g POWERLEVEL9K_GOENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_GOENV_SHOW_SYSTEM=true

  # go_version
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=$C_SUCCESS_ALT
  typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

  # ============================================================
  # Rust 系 - Cyberpunk (ネオンパープル背景)
  # ============================================================
  # rust_version
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

  # ============================================================
  # Ruby 系 - Cyberpunk (ホットピンク背景)
  # ============================================================
  # rbenv
  typeset -g POWERLEVEL9K_RBENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_RBENV_BACKGROUND=$C_ERROR
  typeset -g POWERLEVEL9K_RBENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_RBENV_SHOW_SYSTEM=true

  # rvm
  typeset -g POWERLEVEL9K_RVM_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_RVM_BACKGROUND=$C_ERROR
  typeset -g POWERLEVEL9K_RVM_SHOW_GEMSET=false
  typeset -g POWERLEVEL9K_RVM_SHOW_PREFIX=false

  # ============================================================
  # Java 系 - Cyberpunk (ネオンパープル背景)
  # ============================================================
  # java_version
  typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false

  # jenv
  typeset -g POWERLEVEL9K_JENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_JENV_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_JENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_JENV_SHOW_SYSTEM=true

  # ============================================================
  # PHP 系 - Cyberpunk (ネオンパープル背景)
  # ============================================================
  # php_version
  typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PHP_VERSION_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=true

  # phpenv
  typeset -g POWERLEVEL9K_PHPENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PHPENV_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_PHPENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PHPENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PHPENV_SHOW_SYSTEM=true

  # laravel
  typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_LARAVEL_VERSION_BACKGROUND=$C_ERROR

  # ============================================================
  # .NET 系 - Cyberpunk (ネオンパープル背景)
  # ============================================================
  # dotnet_version
  typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_DOTNET_VERSION_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true

  # ============================================================
  # Perl 系 - Cyberpunk (インディゴ背景)
  # ============================================================
  # plenv
  typeset -g POWERLEVEL9K_PLENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PLENV_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_PLENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PLENV_SHOW_SYSTEM=true

  # perlbrew
  typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PERLBREW_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_PERLBREW_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_PERLBREW_SHOW_PREFIX=false

  # ============================================================
  # Lua 系 - Cyberpunk (インディゴ背景)
  # ============================================================
  # luaenv
  typeset -g POWERLEVEL9K_LUAENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_LUAENV_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_LUAENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_LUAENV_SHOW_SYSTEM=true

  # ============================================================
  # Scala 系 - Cyberpunk (ホットピンク背景)
  # ============================================================
  # scalaenv
  typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_SCALAENV_BACKGROUND=$C_ERROR
  typeset -g POWERLEVEL9K_SCALAENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_SCALAENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_SCALAENV_SHOW_SYSTEM=true

  # ============================================================
  # Haskell 系 - Cyberpunk (ネオンパープル背景)
  # ============================================================
  # haskell_stack
  typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_HASKELL_STACK_BACKGROUND=$C_NEON_PURPLE
  typeset -g POWERLEVEL9K_HASKELL_STACK_SOURCES=(shell local)
  typeset -g POWERLEVEL9K_HASKELL_STACK_ALWAYS_SHOW=true

  # ============================================================
  # Flutter/Dart 系 - Cyberpunk (アクア背景)
  # ============================================================
  # fvm
  typeset -g POWERLEVEL9K_FVM_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_FVM_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # terraform: Terraform ワークスペース
  # ============================================================
  # default ワークスペースは非表示
  typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
  typeset -g POWERLEVEL9K_TERRAFORM_CLASSES=(
      # '*prod*'  PROD
      # '*test*'  TEST
      '*'         OTHER)
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND=$C_NEON_PURPLE

  # ============================================================
  # terraform_version: Terraform バージョン
  # ============================================================
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_BACKGROUND=$C_NEON_PURPLE
  # terraform/tf コマンド入力時のみ表示
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_SHOW_ON_COMMAND='terraform|tf'

  # ============================================================
  # kubecontext: Kubernetes コンテキスト
  # ============================================================
  # kubectl 等のコマンド入力時のみ表示
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
      # '*prod*'  PROD
      # '*test*'  TEST
      '*'       DEFAULT)
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=$C_INDIGO
  # 表示フォーマット (クラスタ名/ネームスペース)
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=
  POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
  POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'

  # ============================================================
  # aws: AWS プロファイル
  # ============================================================
  # aws 等のコマンド入力時のみ表示
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|cdk|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AWS_CLASSES=(
      # '*prod*'  PROD
      # '*test*'  TEST
      '*'       DEFAULT)
  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=$C_NEON_PURPLE
  # 表示フォーマット (プロファイル名 リージョン)
  typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='${P9K_AWS_PROFILE//\%/%%}${P9K_AWS_REGION:+ ${P9K_AWS_REGION//\%/%%}}'

  # ============================================================
  # aws_eb_env: AWS Elastic Beanstalk
  # ============================================================
  typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_AWS_EB_ENV_BACKGROUND=$C_NEON_PURPLE

  # ============================================================
  # azure: Azure アカウント
  # ============================================================
  # az 等のコマンド入力時のみ表示
  typeset -g POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AZURE_CLASSES=(
      # '*prod*'  PROD
      # '*test*'  TEST
      '*'         OTHER)
  typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_AZURE_OTHER_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # gcloud: Google Cloud
  # ============================================================
  # gcloud 等のコマンド入力時のみ表示
  typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=$C_INDIGO
  # プロジェクト名取得前
  typeset -g POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_ID//\%/%%}'
  # プロジェクト名取得後
  typeset -g POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_NAME//\%/%%}'
  # プロジェクト名の更新間隔 (秒 / 負数=設定変更時のみ)
  typeset -g POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60

  # ============================================================
  # google_app_cred: Google 認証情報
  # ============================================================
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND='terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=(
      # '*:*prod*:*'  PROD
      # '*:*test*:*'  TEST
      '*'             DEFAULT)
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_BACKGROUND=$C_INDIGO
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION='${P9K_GOOGLE_APP_CRED_PROJECT_ID//\%/%%}'

  # ============================================================
  # toolbox: Toolbox 名
  # ============================================================
  typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_TOOLBOX_BACKGROUND=$C_SUCCESS_ALT
  # fedora-toolbox-* は非表示
  typeset -g POWERLEVEL9K_TOOLBOX_CONTENT_EXPANSION='${P9K_TOOLBOX_NAME:#fedora-toolbox-*}'

  # ============================================================
  # public_ip: パブリック IP
  # ============================================================
  typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_PUBLIC_IP_BACKGROUND=$C_DARK

  # ============================================================
  # vpn_ip: VPN 接続状態
  # ============================================================
  typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_VPN_IP_BACKGROUND=$C_SUCCESS
  # アイコンのみ表示 (IP アドレスは非表示)
  typeset -g POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION=
  # VPN インターフェース名のパターン
  typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='(gpd|wg|(.*tun)|tailscale)[0-9]*|(zt.*)'
  # 全インターフェース表示
  typeset -g POWERLEVEL9K_VPN_IP_SHOW_ALL=false

  # ============================================================
  # ip: IP アドレス / 帯域
  # ============================================================
  typeset -g POWERLEVEL9K_IP_BACKGROUND=$C_SUCCESS_ALT
  typeset -g POWERLEVEL9K_IP_FOREGROUND=$C_BLACK
  # 表示フォーマット (受信レート 送信レート IP)
  typeset -g POWERLEVEL9K_IP_CONTENT_EXPANSION='${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'
  # 対象インターフェース名のパターン
  typeset -g POWERLEVEL9K_IP_INTERFACE='[ew].*'

  # ============================================================
  # proxy: プロキシ設定
  # ============================================================
  typeset -g POWERLEVEL9K_PROXY_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_PROXY_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # battery: バッテリー
  # ============================================================
  # 低残量の閾値 (%)
  typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=$C_ERROR
  # 充電中/満充電
  typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=$C_SUCCESS
  # 放電中
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=$C_WARNING
  # バッテリーアイコン (低→高)
  typeset -g POWERLEVEL9K_BATTERY_STAGES='\UF008E\UF007A\UF007B\UF007C\UF007D\UF007E\UF007F\UF0080\UF0081\UF0082\UF0079'
  # 残り時間を非表示
  typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
  typeset -g POWERLEVEL9K_BATTERY_BACKGROUND=$C_DARK

  # ============================================================
  # wifi: WiFi 速度
  # ============================================================
  typeset -g POWERLEVEL9K_WIFI_FOREGROUND=$C_BLACK
  typeset -g POWERLEVEL9K_WIFI_BACKGROUND=$C_SUCCESS_ALT

  # ============================================================
  # time: 現在時刻
  # ============================================================
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=$C_DARK
  # 表示フォーマット (HH:MM:SS)
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  # コマンド実行時に時刻を更新
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # ============================================================
  # カスタムセグメント例
  # ============================================================
  function prompt_example() {
    p10k segment -b $C_ERROR -f $C_WHITE -i '⭐' -t 'hello, %n'
  }

  # instant prompt 用
  function instant_prompt_example() {
    prompt_example
  }

  typeset -g POWERLEVEL9K_EXAMPLE_FOREGROUND=$C_WHITE
  typeset -g POWERLEVEL9K_EXAMPLE_BACKGROUND=$C_ERROR

  # ============================================================
  # Transient Prompt
  # ============================================================
  # off: 無効 / always: 常に / same-dir: ディレクトリ変更時以外
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # ============================================================
  # Instant Prompt
  # ============================================================
  # off: 無効 / quiet: 警告なし / verbose: 警告あり
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # ============================================================
  # Hot Reload
  # ============================================================
  # true: 無効 (1-2ms 高速化)
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # 設定再読込
  (( ! $+functions[p10k] )) || p10k reload
}

# p10k configure が上書きするファイル
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
